- name: Create IntelliJ config path if not exists
  file:
    path: "/home/boostem/.config/JetBrains/IntelliJIdea2025.1/options"
    state: directory
    owner: boostem
    group: boostem
    mode: '0755'

- name: Configure IntelliJ UI settings
  copy:
    dest: "/home/boostem/.config/JetBrains/IntelliJIdea2025.1/options/ui.lnf.xml"
    content: |
      <application>
        <component name="UISettings">
          <property name="TREE_INDENT" value="8" />
          <property name="FOLLOW_CURRENT_EDITOR" value="true" />
          <property name="THEME" value="Darcula" />
        </component>
      </application>
    owner: boostem
    group: boostem
    mode: '0644'

- name: Install Obsidian via Flatpak
  flatpak:
    name: md.obsidian.Obsidian
    state: present

- name: Ensure VS Code config directory exists
  file:
    path: /home/boostem/.config/Code/User
    state: directory
    owner: boostem
    group: boostem
    mode: '0755'
