- name: Uninstall dev tools and config (safe)
  hosts: localhost
  become: true
  tasks:
    - name: Remove packages
      dnf:
        name:
          - git
          - curl
          - htop
          - nmap
          - nodejs
          - maven
        state: absent

    - name: Stop and disable Docker service
      systemd:
        name: docker
        state: stopped
        enabled: false

    - name: Remove Docker binaries
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/bin/docker
        - /usr/bin/dockerd
        - /usr/bin/docker-compose

    - name: Remove IntelliJ installation directory
      file:
        path: "/opt/intellij"
        state: absent

    - name: Remove IntelliJ config
      file:
        path: "/home/boostem/.config/JetBrains"
        state: absent

    - name: Uninstall Obsidian flatpak
      command: flatpak uninstall -y md.obsidian.Obsidian
      ignore_errors: true
